top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/aaa
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/aaa
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/aaa

include $(top_srcdir)/build/special.mk

