top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/cache
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/cache
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/cache

include $(top_srcdir)/build/special.mk

