top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/mappers
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/mappers
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/mappers

include $(top_srcdir)/build/special.mk

