top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/os
builddir     = /home/apache/toolwork/httpd-2.4.18/os
VPATH        = /home/apache/toolwork/httpd-2.4.18/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
