top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/metadata
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/metadata
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/metadata

include $(top_srcdir)/build/special.mk

