top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/echo
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/echo
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/echo

include $(top_srcdir)/build/special.mk

