top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/dav/main
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/dav/main
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
