top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/arch/unix
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/arch/unix
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/arch/unix

include $(top_srcdir)/build/special.mk

