top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/generators
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/generators
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/generators

include $(top_srcdir)/build/special.mk

