top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/server/mpm
builddir     = /home/apache/toolwork/httpd-2.4.18/server/mpm
VPATH        = /home/apache/toolwork/httpd-2.4.18/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
