top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/server/mpm/prefork
builddir     = /home/apache/toolwork/httpd-2.4.18/server/mpm/prefork
VPATH        = /home/apache/toolwork/httpd-2.4.18/server/mpm/prefork
include $(top_srcdir)/build/special.mk
