top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/loggers
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/loggers
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/loggers

include $(top_srcdir)/build/special.mk

