top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/filters
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/filters
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/filters

include $(top_srcdir)/build/special.mk

