top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules
builddir     = /home/apache/toolwork/httpd-2.4.18/modules
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

