top_srcdir   = /home/apache/toolwork/httpd-2.4.18
top_builddir = /home/apache/toolwork/httpd-2.4.18
srcdir       = /home/apache/toolwork/httpd-2.4.18/modules/http
builddir     = /home/apache/toolwork/httpd-2.4.18/modules/http
VPATH        = /home/apache/toolwork/httpd-2.4.18/modules/http

include $(top_srcdir)/build/special.mk

